-- [02_create_raw_tables.sql]
-- 원천 데이터 테이블 생성
USE DATABASE ONTOLOGY_EDU;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(100),
    SEGMENT VARCHAR(50),
    REGION VARCHAR(50),
    RISK_TIER VARCHAR(10)
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10, 2)
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID VARCHAR(10) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(10),
    ORDER_DATE DATE,
    STATUS VARCHAR(20)
);

CREATE OR REPLACE TABLE ORDER_ITEMS (
    ITEM_ID VARCHAR(10) PRIMARY KEY,
    ORDER_ID VARCHAR(10),
    PRODUCT_ID VARCHAR(10),
    QUANTITY NUMBER(10)
);

-- 샘플 데이터 삽입
INSERT INTO CUSTOMERS VALUES ('C001', 'Global Tech', 'Enterprise', 'NA', 'Low'), ('C002', 'Asia Retail', 'SMB', 'APAC', 'Medium');
INSERT INTO PRODUCTS VALUES ('P001', 'Cloud Suite', 'Software', 500.00), ('P002', 'Data Guard', 'Security', 300.00);
INSERT INTO ORDERS VALUES ('O001', 'C001', '2024-05-01', 'Submitted'), ('O002', 'C002', '2024-05-02', 'Pending');
INSERT INTO ORDER_ITEMS VALUES ('I001', 'O001', 'P001', 10), ('I002', 'O001', 'P002', 5), ('I003', 'O002', 'P001', 2);
