-- [03_create_ontology_views.sql]
-- 온톨로지 객체 및 관계 뷰 생성
USE DATABASE ONTOLOGY_EDU;
USE SCHEMA ONTOLOGY;

-- 1. 객체 뷰 (Object Views)
CREATE OR REPLACE VIEW CUSTOMER_OBJECT AS
SELECT CUSTOMER_ID, NAME, SEGMENT, REGION, RISK_TIER 
FROM RAW.CUSTOMERS;

CREATE OR REPLACE VIEW ORDER_OBJECT AS
SELECT 
    O.ORDER_ID, O.CUSTOMER_ID, O.ORDER_DATE, O.STATUS,
    SUM(I.QUANTITY * P.UNIT_PRICE) AS TOTAL_AMOUNT  -- 계산 속성
FROM RAW.ORDERS O
JOIN RAW.ORDER_ITEMS I ON O.ORDER_ID = I.ORDER_ID
JOIN RAW.PRODUCTS P ON I.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 1, 2, 3, 4;

-- 2. 관계 뷰 (Relationship Views)
CREATE OR REPLACE VIEW REL_CUSTOMER_PLACED_ORDER AS
SELECT CUSTOMER_ID, ORDER_ID FROM RAW.ORDERS;
