-- [04_create_workflow_actions.sql]
-- 액션 및 워크플로우 구현
USE DATABASE ONTOLOGY_EDU;
USE SCHEMA ONTOLOGY;

-- 액션 기록용 테이블
CREATE OR REPLACE TABLE ACTION_LOG (
    ACTION_ID INT AUTOINCREMENT,
    ACTION_NAME VARCHAR(50),
    TARGET_ID VARCHAR(50),
    ACTOR VARCHAR(50),
    COMMENT VARCHAR(200),
    OCCURRED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA APP;

-- 주문 승인 액션 프로시저
CREATE OR REPLACE PROCEDURE APPROVE_ORDER(ORDER_ID VARCHAR, ACTOR VARCHAR, COMMENT VARCHAR)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- 1. 상태 변경
    UPDATE RAW.ORDERS 
    SET STATUS = 'Approved' 
    WHERE ORDER_ID = :ORDER_ID;
    
    -- 2. 액션 로그 기록
    INSERT INTO ONTOLOGY.ACTION_LOG (ACTION_NAME, TARGET_ID, ACTOR, COMMENT)
    VALUES ('ApproveOrder', :ORDER_ID, :ACTOR, :COMMENT);
    
    RETURN 'Order ' || :ORDER_ID || ' has been approved.';
END;
$$;
