-- [05_business_queries.sql]
-- 업무용 조회 쿼리 예시
USE DATABASE ONTOLOGY_EDU;
USE SCHEMA ONTOLOGY;

-- 1. 특정 고객의 주문 현황 및 총액 탐색
SELECT 
    C.NAME AS CUSTOMER_NAME,
    O.ORDER_ID,
    O.TOTAL_AMOUNT,
    O.STATUS
FROM CUSTOMER_OBJECT C
JOIN REL_CUSTOMER_PLACED_ORDER R ON C.CUSTOMER_ID = R.CUSTOMER_ID
JOIN ORDER_OBJECT O ON R.ORDER_ID = O.ORDER_ID
WHERE C.NAME = 'Global Tech';

-- 2. 최근 실행된 액션 이력 조회
SELECT * FROM ACTION_LOG 
ORDER BY OCCURRED_AT DESC;
