-- [05_business_queries.sql]
-- 업무용 조회 쿼리 예시
USE DATABASE ONTOLOGY_EDU;

USE SCHEMA APP;

CREATE OR REPLACE VIEW ORDER_REVIEW_QUEUE AS
SELECT
    O.OBJECT_ID AS ORDER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_VALUE_TIER,
    O.ORDER_DATE,
    O.STATUS,
    O.ORDER_AMOUNT
FROM ONTOLOGY.ORDER_OBJECT O
JOIN ONTOLOGY.CUSTOMER_ENRICHED_OBJECT C
    ON O.CUSTOMER_ID = C.OBJECT_ID
WHERE O.STATUS = 'Submitted'
ORDER BY O.ORDER_AMOUNT DESC;

-- 1. 특정 고객의 주문 현황 및 총액 탐색
SELECT
    C.CUSTOMER_NAME,
    O.OBJECT_ID AS ORDER_ID,
    O.ORDER_AMOUNT,
    O.STATUS
FROM ONTOLOGY.CUSTOMER_OBJECT C
JOIN ONTOLOGY.CUSTOMER_ORDER_RELATION R
    ON C.OBJECT_ID = R.SOURCE_OBJECT_ID
JOIN ONTOLOGY.ORDER_OBJECT O
    ON R.TARGET_OBJECT_ID = O.OBJECT_ID
WHERE C.CUSTOMER_NAME = 'Alpha Manufacturing';

-- 2. 주문 검토 큐 조회
SELECT * FROM ORDER_REVIEW_QUEUE;

-- 3. 최근 액션 요청 조회
SELECT *
FROM ACTION_REQUESTS
ORDER BY REQUESTED_AT DESC;
