-- [01_setup_database.sql]
CREATE OR REPLACE DATABASE ONTOLOGY_EDU;
USE DATABASE ONTOLOGY_EDU;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA ONTOLOGY;
CREATE OR REPLACE SCHEMA APP;

-- [02_create_raw_tables.sql]
USE SCHEMA RAW;
CREATE OR REPLACE TABLE CUSTOMERS (CUSTOMER_ID VARCHAR(10) PRIMARY KEY, NAME VARCHAR(100), SEGMENT VARCHAR(50), REGION VARCHAR(50), RISK_TIER VARCHAR(10));
CREATE OR REPLACE TABLE PRODUCTS (PRODUCT_ID VARCHAR(10) PRIMARY KEY, NAME VARCHAR(100), CATEGORY VARCHAR(50), UNIT_PRICE NUMBER(10, 2));
CREATE OR REPLACE TABLE ORDERS (ORDER_ID VARCHAR(10) PRIMARY KEY, CUSTOMER_ID VARCHAR(10), ORDER_DATE DATE, STATUS VARCHAR(20));
CREATE OR REPLACE TABLE ORDER_ITEMS (ITEM_ID VARCHAR(10) PRIMARY KEY, ORDER_ID VARCHAR(10), PRODUCT_ID VARCHAR(10), QUANTITY NUMBER(10));
INSERT INTO CUSTOMERS VALUES ('C001', 'Global Tech', 'Enterprise', 'NA', 'Low'), ('C002', 'Asia Retail', 'SMB', 'APAC', 'Medium');
INSERT INTO PRODUCTS VALUES ('P001', 'Cloud Suite', 'Software', 500.00), ('P002', 'Data Guard', 'Security', 300.00);
INSERT INTO ORDERS VALUES ('O001', 'C001', '2024-05-01', 'Submitted'), ('O002', 'C002', '2024-05-02', 'Pending');
INSERT INTO ORDER_ITEMS VALUES ('I001', 'O001', 'P001', 10), ('I002', 'O001', 'P002', 5), ('I003', 'O002', 'P001', 2);

-- [03_create_ontology_views.sql]
USE SCHEMA ONTOLOGY;
CREATE OR REPLACE VIEW CUSTOMER_OBJECT AS SELECT CUSTOMER_ID, NAME, SEGMENT, REGION, RISK_TIER FROM RAW.CUSTOMERS;
CREATE OR REPLACE VIEW ORDER_OBJECT AS SELECT O.ORDER_ID, O.CUSTOMER_ID, O.ORDER_DATE, O.STATUS, SUM(I.QUANTITY * P.UNIT_PRICE) AS TOTAL_AMOUNT FROM RAW.ORDERS O JOIN RAW.ORDER_ITEMS I ON O.ORDER_ID = I.ORDER_ID JOIN RAW.PRODUCTS P ON I.PRODUCT_ID = P.PRODUCT_ID GROUP BY 1, 2, 3, 4;
CREATE OR REPLACE VIEW REL_CUSTOMER_PLACED_ORDER AS SELECT CUSTOMER_ID, ORDER_ID FROM RAW.ORDERS;

-- [04_create_workflow_actions.sql]
USE SCHEMA ONTOLOGY;
CREATE OR REPLACE TABLE ACTION_LOG (ACTION_ID INT AUTOINCREMENT, ACTION_NAME VARCHAR(50), TARGET_ID VARCHAR(50), ACTOR VARCHAR(50), COMMENT VARCHAR(200), OCCURRED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());
USE SCHEMA APP;
CREATE OR REPLACE PROCEDURE APPROVE_ORDER(ORDER_ID VARCHAR, ACTOR VARCHAR, COMMENT VARCHAR) RETURNS STRING LANGUAGE SQL AS $$ BEGIN UPDATE RAW.ORDERS SET STATUS = 'Approved' WHERE ORDER_ID = :ORDER_ID; INSERT INTO ONTOLOGY.ACTION_LOG (ACTION_NAME, TARGET_ID, ACTOR, COMMENT) VALUES ('ApproveOrder', :ORDER_ID, :ACTOR, :COMMENT); RETURN 'Order ' || :ORDER_ID || ' has been approved.'; END; $$;
