-- [03_create_ontology_views.sql]
-- 온톨로지 객체 및 관계 뷰 생성
USE DATABASE ONTOLOGY_EDU;
USE SCHEMA ONTOLOGY;

-- 1. 객체 뷰 (Object Views)
CREATE OR REPLACE VIEW CUSTOMER_OBJECT AS
SELECT
    CUSTOMER_ID AS OBJECT_ID,
    CUSTOMER_NAME,
    SEGMENT,
    REGION,
    CREATED_AT
FROM RAW.CUSTOMERS;

CREATE OR REPLACE VIEW PRODUCT_OBJECT AS
SELECT
    PRODUCT_ID AS OBJECT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
FROM RAW.PRODUCTS;

CREATE OR REPLACE VIEW ORDER_OBJECT AS
SELECT
    O.ORDER_ID AS OBJECT_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.STATUS,
    SUM(I.QUANTITY * P.UNIT_PRICE) AS ORDER_AMOUNT
FROM RAW.ORDERS O
JOIN RAW.ORDER_ITEMS I
    ON O.ORDER_ID = I.ORDER_ID
JOIN RAW.PRODUCTS P
    ON I.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.STATUS;

-- 2. 관계 뷰 (Relationship Views)
CREATE OR REPLACE VIEW CUSTOMER_ORDER_RELATION AS
SELECT
    CUSTOMER_ID AS SOURCE_OBJECT_ID,
    ORDER_ID AS TARGET_OBJECT_ID,
    'CUSTOMER_PLACED_ORDER' AS RELATION_TYPE
FROM RAW.ORDERS;

CREATE OR REPLACE VIEW ORDER_PRODUCT_RELATION AS
SELECT
    ORDER_ID AS SOURCE_OBJECT_ID,
    PRODUCT_ID AS TARGET_OBJECT_ID,
    'ORDER_CONTAINS_PRODUCT' AS RELATION_TYPE,
    QUANTITY
FROM RAW.ORDER_ITEMS;

-- 3. 계산 속성 뷰 (Computed Properties)
CREATE OR REPLACE VIEW CUSTOMER_ENRICHED_OBJECT AS
SELECT
    C.OBJECT_ID,
    C.CUSTOMER_NAME,
    C.SEGMENT,
    C.REGION,
    COUNT(O.OBJECT_ID) AS ORDER_COUNT,
    COALESCE(SUM(O.ORDER_AMOUNT), 0) AS TOTAL_ORDER_AMOUNT,
    CASE
        WHEN COALESCE(SUM(O.ORDER_AMOUNT), 0) >= 5000 THEN 'High'
        WHEN COALESCE(SUM(O.ORDER_AMOUNT), 0) >= 1000 THEN 'Medium'
        ELSE 'Low'
    END AS CUSTOMER_VALUE_TIER
FROM CUSTOMER_OBJECT C
LEFT JOIN ORDER_OBJECT O
    ON C.OBJECT_ID = O.CUSTOMER_ID
GROUP BY
    C.OBJECT_ID,
    C.CUSTOMER_NAME,
    C.SEGMENT,
    C.REGION;
