-- [01_setup_database.sql]
CREATE OR REPLACE DATABASE ONTOLOGY_EDU;
USE DATABASE ONTOLOGY_EDU;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA ONTOLOGY;
CREATE OR REPLACE SCHEMA APP;

-- [02_create_raw_tables.sql]
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(10) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    SEGMENT VARCHAR(50),
    REGION VARCHAR(50),
    CREATED_AT DATE
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(10) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10, 2)
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID VARCHAR(10) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(10),
    ORDER_DATE DATE,
    STATUS VARCHAR(20)
);

CREATE OR REPLACE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID VARCHAR(10) PRIMARY KEY,
    ORDER_ID VARCHAR(10),
    PRODUCT_ID VARCHAR(10),
    QUANTITY NUMBER(10, 0)
);

INSERT INTO CUSTOMERS VALUES
('C001', 'Alpha Manufacturing', 'Enterprise', 'Seoul', '2025-01-10'),
('C002', 'Beta Retail', 'SMB', 'Busan', '2025-02-15'),
('C003', 'Gamma Logistics', 'Enterprise', 'Incheon', '2025-03-20');

INSERT INTO PRODUCTS VALUES
('P001', 'Industrial Sensor', 'Hardware', 250.00),
('P002', 'Analytics License', 'Software', 1200.00),
('P003', 'Support Package', 'Service', 500.00);

INSERT INTO ORDERS VALUES
('O001', 'C001', '2026-04-01', 'Submitted'),
('O002', 'C001', '2026-04-03', 'Approved'),
('O003', 'C002', '2026-04-05', 'Submitted');

INSERT INTO ORDER_ITEMS VALUES
('OI001', 'O001', 'P001', 10),
('OI002', 'O001', 'P003', 1),
('OI003', 'O002', 'P002', 3),
('OI004', 'O003', 'P001', 2);

-- [03_create_ontology_views.sql]
USE SCHEMA ONTOLOGY;

CREATE OR REPLACE VIEW CUSTOMER_OBJECT AS
SELECT
    CUSTOMER_ID AS OBJECT_ID,
    CUSTOMER_NAME,
    SEGMENT,
    REGION,
    CREATED_AT
FROM RAW.CUSTOMERS;

CREATE OR REPLACE VIEW PRODUCT_OBJECT AS
SELECT
    PRODUCT_ID AS OBJECT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
FROM RAW.PRODUCTS;

CREATE OR REPLACE VIEW ORDER_OBJECT AS
SELECT
    O.ORDER_ID AS OBJECT_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.STATUS,
    SUM(OI.QUANTITY * P.UNIT_PRICE) AS ORDER_AMOUNT
FROM RAW.ORDERS O
JOIN RAW.ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
JOIN RAW.PRODUCTS P
    ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.STATUS;

CREATE OR REPLACE VIEW CUSTOMER_ORDER_RELATION AS
SELECT
    CUSTOMER_ID AS SOURCE_OBJECT_ID,
    ORDER_ID AS TARGET_OBJECT_ID,
    'CUSTOMER_PLACED_ORDER' AS RELATION_TYPE
FROM RAW.ORDERS;

CREATE OR REPLACE VIEW ORDER_PRODUCT_RELATION AS
SELECT
    ORDER_ID AS SOURCE_OBJECT_ID,
    PRODUCT_ID AS TARGET_OBJECT_ID,
    'ORDER_CONTAINS_PRODUCT' AS RELATION_TYPE,
    QUANTITY
FROM RAW.ORDER_ITEMS;

CREATE OR REPLACE VIEW CUSTOMER_ENRICHED_OBJECT AS
SELECT
    C.OBJECT_ID,
    C.CUSTOMER_NAME,
    C.SEGMENT,
    C.REGION,
    COUNT(O.OBJECT_ID) AS ORDER_COUNT,
    COALESCE(SUM(O.ORDER_AMOUNT), 0) AS TOTAL_ORDER_AMOUNT,
    CASE
        WHEN COALESCE(SUM(O.ORDER_AMOUNT), 0) >= 5000 THEN 'High'
        WHEN COALESCE(SUM(O.ORDER_AMOUNT), 0) >= 1000 THEN 'Medium'
        ELSE 'Low'
    END AS CUSTOMER_VALUE_TIER
FROM CUSTOMER_OBJECT C
LEFT JOIN ORDER_OBJECT O
    ON C.OBJECT_ID = O.CUSTOMER_ID
GROUP BY
    C.OBJECT_ID,
    C.CUSTOMER_NAME,
    C.SEGMENT,
    C.REGION;

-- [04_create_workflow_actions.sql]
USE SCHEMA APP;

CREATE OR REPLACE TABLE ACTION_REQUESTS (
    ACTION_ID STRING DEFAULT UUID_STRING(),
    OBJECT_TYPE STRING,
    OBJECT_ID STRING,
    ACTION_TYPE STRING,
    REQUESTED_BY STRING,
    REQUESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PAYLOAD VARIANT,
    STATUS STRING DEFAULT 'Requested'
);

CREATE OR REPLACE PROCEDURE REQUEST_APPROVE_ORDER(ORDER_ID STRING, REQUESTED_BY STRING, COMMENT STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO ACTION_REQUESTS (
        OBJECT_TYPE,
        OBJECT_ID,
        ACTION_TYPE,
        REQUESTED_BY,
        PAYLOAD
    )
    SELECT
        'Order',
        OBJECT_ID,
        'ApproveOrder',
        :REQUESTED_BY,
        OBJECT_CONSTRUCT(
            'previous_status', STATUS,
            'order_amount', ORDER_AMOUNT,
            'comment', :COMMENT
        )
    FROM ONTOLOGY.ORDER_OBJECT
    WHERE OBJECT_ID = :ORDER_ID;

    RETURN 'ApproveOrder request has been recorded for order ' || :ORDER_ID || '.';
END;
$$;

-- [05_business_queries.sql]
CREATE OR REPLACE VIEW ORDER_REVIEW_QUEUE AS
SELECT
    O.OBJECT_ID AS ORDER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_VALUE_TIER,
    O.ORDER_DATE,
    O.STATUS,
    O.ORDER_AMOUNT
FROM ONTOLOGY.ORDER_OBJECT O
JOIN ONTOLOGY.CUSTOMER_ENRICHED_OBJECT C
    ON O.CUSTOMER_ID = C.OBJECT_ID
WHERE O.STATUS = 'Submitted'
ORDER BY O.ORDER_AMOUNT DESC;
